CREATE TABLE IF NOT EXISTS rag_intent_node (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Intent node ID',
    user_id BIGINT NOT NULL COMMENT 'Owner user ID',
    parent_id BIGINT NULL COMMENT 'Parent intent node ID',
    intent_code VARCHAR(64) NOT NULL COMMENT 'Stable intent code',
    name VARCHAR(100) NOT NULL COMMENT 'Intent display name',
    description VARCHAR(500) NULL COMMENT 'Intent description',
    level VARCHAR(20) NOT NULL COMMENT 'DOMAIN, CATEGORY, or TOPIC',
    kind VARCHAR(20) NOT NULL DEFAULT 'KB' COMMENT 'KB, SYSTEM, or MCP',
    knowledge_base_id BIGINT NULL COMMENT 'Target knowledge base for KB intents',
    mcp_tool_id BIGINT NULL COMMENT 'Target MCP tool for MCP intents',
    top_k INT NOT NULL DEFAULT 5 COMMENT 'Retrieval topK for this intent',
    route_config JSON NULL COMMENT 'Advanced route configuration',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '0 disabled, 1 enabled',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Sibling sort order',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_rag_intent_user_code_deleted (user_id, intent_code, deleted),
    KEY idx_rag_intent_user_parent (user_id, parent_id, deleted, sort_order),
    KEY idx_rag_intent_kb (knowledge_base_id),
    CONSTRAINT fk_rag_intent_kb FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG intent tree nodes';
